input User { 
    Id: ID 
    Name: String
    passwordHash: String
    shippingAddress: String
    phone: String
    email: String
    Dob: String
}


type Mutation {
    signUp(user: User!): Boolean
    updateUser(user: User!): Boolean
    deleteUser(userId:ID!): Boolean
}

type Query {
    logIn(email:String! passwordHash:String!): ID
}